[build]
  publish   = "."
  functions = "netlify/functions"

# === Redirections API vers Netlify Functions ===
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# === Admin ===
# URL raccourcie vers ton dashboard
[[redirects]]
  from = "/admin"
  to   = "/admin-dashboard.html"
  status = 200

# Tu peux aussi forcer tous les /admin/* vers la page dashboard si tu veux
[[redirects]]
  from = "/admin/*"
  to   = "/admin-dashboard.html"
  status = 200

# === Tâche planifiée ===
[[scheduled.functions]]
  name = "prune-users"
  cron = "0 3 * * *"
